### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by sumnerevans** [jackrosenthal/lug-docutils-presentation#1]
I am getting an error when I try to `make`:

    $ make
    make: *** No rule to make target 'out/lug-docutils-43.pdf', needed by 'all'.  Stop.

**Comment by jackrosenthal** [comment]
Thanks... that was the result of writing a gitignore too fast and excluding graphics/lug.pdf (which I was not using anyway!)

**Comment by jackrosenthal** [comment]
P.S. I'm going to write a "quicksetup" script for lug presentations soon that will include relevant Makefiles, etc.

Stay tuned!
